# Generated by Django 2.0 on 2020-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
