# Generated by Django 2.0 on 2020-04-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0002_auto_20200410_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(),
        ),
    ]
