# Generated by Django 3.0.5 on 2020-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0004_auto_20200410_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='stat',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
