# Generated by Django 3.0.5 on 2020-05-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0010_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
