# Generated by Django 3.0.5 on 2020-05-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0011_remove_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
