# Generated by Django 3.0.5 on 2020-05-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0014_auto_20200506_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
