# Generated by Django 3.0.5 on 2020-05-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0017_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
