# Generated by Django 3.0.5 on 2020-05-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0019_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
