# Generated by Django 3.0.5 on 2020-05-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0021_auto_20200514_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
