# Generated by Django 3.0.5 on 2020-05-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0024_pimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PImages',
        ),
    ]
