# Generated by Django 3.0.5 on 2020-04-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_contactformmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='references',
        ),
    ]
