# Generated by Django 3.0.5 on 2020-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_faq_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='linkedin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
