# Generated by Django 3.0.5 on 2020-05-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0020_auto_20200513_2058'),
        ('content', '0003_auto_20200510_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Human.Comment'),
        ),
    ]
