# Generated by Django 3.0.5 on 2020-05-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0022_remove_comment_content'),
        ('content', '0005_remove_content_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Human.Comment'),
        ),
    ]
